[default.databases.sqlitedb]
url = "db/backend-sqlite.db"

[release]
address = "0.0.0.0"
port = 443
workers = 1
log_level = "normal"

[release.tls]
certs = "/certs/fullchain.pem"
key = "/certs/privkey.pem"
